server:
  port: 8080
spring:
  profiles:
    active: dev
  messages:
    basename: static/i18n/messages #相对路径 开头请勿添加斜杠
    useCodeAsDefaultMessage: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  cache:
    jcache:
      config: classpath:ehcache.xml
  mobile:
    devicedelegatingviewresolver:
      enabled: false # 必须开启才能使用devicedelegatingviewresolver功能
      #     normalPrefix: normal/
      mobilePrefix: mobile/
      tabletPrefix: tablet/
      enableFallback: true # 有问题
    sitepreference: # 参数
      enabled: false # 开启,可以指定参数
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  mail:  # SMTP 发邮件
    host: smtp.qiye.aliyun.com
    port: 25
    username: xxx
    password: xxx
    default-encoding: UTF-8
    imap: # IMAP 收邮件
      host: imap.qiye.aliyun.com
      port: 143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.rick.admin: DEBUG
    com.rick.db: DEBUG
  file:
    path: /Users/rick/Space/tmp/admin/log

sharp:
  database:
    entity-base-package: com.rick.admin.module.**.entity

dict:
  items:
    - type: sys_user
      sql: "select id, name from sys_user order by id asc"
    - type: sys_role
      sql: "select id, name from sys_role order by id asc"
    - type: core_material_category
      sql: "select 0 as id, '无' from dual union all select id, name from core_material_category order by id asc"
    - type: partner_type
      map: { "VENDOR": "供应商", "CUSTOMER": "客户"}
    - type: core_partner
      sql: "select id, name from core_partner WHERE is_deleted = 0 order by id asc"
    - type: core_partner_vendor
      sql: "select id, name from core_partner where partner_type = 'VENDOR' AND is_deleted = 0 order by name asc"
    - type: core_partner_customer
      sql: "select id, name from core_partner where partner_type = 'CUSTOMER' AND is_deleted = 0 order by name asc"
    - type: core_plant
      sql: "select id, name from core_plant where is_deleted = 0 order by id asc"
    - type: sys_dict_type
      sql: "select distinct type, type from sys_dict order by sort asc"
    - type: unit
      sql: "select name, label from sys_dict where type = 'UNIT' order by sort asc"
    - type: material_type
      sql: "select name, label from sys_dict where type = 'MATERIAL_TYPE' order by sort asc"
    - type: bom_material
      sql: "select id name, name label from mm_material where bom_template_id is NOT NULL"
    - type: material_bom
      sql: "select id name, concat(code, '-' ,description) label from produce_bom_template"
    - type: core_classification
      sql: "select code, description from `core_classification`"
    - type: bol
      map: { "1": "是", "0": "否" }
    - type: mm_material
      sql: "select id, name from mm_material order by id asc"
    - type: movement_type
      map: { "INBOUND": "入库", "OUTBOUND": "出库" }
    - type: inv_type
      map: { "INBOUND": "收货", "OUTBOUND": "出货", "RETURN": "退货", "MOVING_TO_PRODUCE": "领料", "RETURN_FROM_PRODUCE": "退料", "CANCEL":"取消", "COUNT": "盘点"}
    - type: reference_type
      map: { "OTHER": "无","MATERIAL_DOCUMENT": "物料凭证", "PO": "采购订单", "PDO": "生产单", "SO": "生产单"}
    - type: produce_order_status
      map: { "PLANNING": "计划中","PROCESSING": "完成领料", "PRODUCED": "生产完成", "DONE": "订单完成"}
    - type: purchase_order_status
      map: { "PLANNING": "采购中", "DONE": "采购完成"}

props:
  items: {"material_category_select_sql": "select id, name, (select name from core_material_category where c1.parent_id = id) parent_name from `core_material_category` c1 where id not in(719894871824945152, 719894910232186880, 719894937591631872, 719895017157578752)"}


fileupload:
  tmp: /Users/rick/Space/tmp/fastdfs/tmp # 下载的临时目录
  local: # cd /Users/rick/Space/tmp/fileupload && http-server -p 7892
    root-path: /Users/rick/Space/tmp/fileupload
    server-url: http://localhost:7892/ # 映射到tmp目录
