spring:
  profiles:
    active: dev
  messages:
    basename: static/i18n/messages #相对路径 开头请勿添加斜杠
    useCodeAsDefaultMessage: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  cache:
    jcache:
      config: classpath:ehcache.xml
  mobile:
    devicedelegatingviewresolver:
      enabled: false # 必须开启才能使用devicedelegatingviewresolver功能
      #     normalPrefix: normal/
      mobilePrefix: mobile/
      tabletPrefix: tablet/
      enableFallback: true # 有问题
    sitepreference: # 参数
      enabled: false # 开启,可以指定参数
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sharp-admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password:
      initialSize: 1
      minIdle: 5
      maxActive: 10
      maxWait: 60000
  mail:  # SMTP 发邮件
    host: smtp.qiye.aliyun.com
    port: 25
    username: xxx
    password: xxx
    default-encoding: UTF-8
    imap: # IMAP 收邮件
      host: imap.qiye.aliyun.com
      port: 143
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    com.rick.admin: DEBUG
    com.rick.db: DEBUG
  file:
    path: /Users/rick/Space/tmp/admin/log

dict:
  items:
    - type: user
      sql: "select cast(id as char(20)) id, name from sys_user order by id asc"
    - type: sys_role
      sql: "select cast(id as char(20)) id, name from sys_role order by id asc"
    - type: dict-type
      sql: "select type, type from sys_dict"
    - type: grade
      map: {g1: "一年级", g2: "二年级"}
    - type: bol
      map: { "1" : "是", "0": "否" }
    - type: status
      map: {LOCKED: "锁定", NORMAL: "正常"}
    - type: nativePlace #  有中文不能使用 map: { "江苏": "江苏", "四川": "四川", "陕西": "陕西", "上海": "上海" }
      list:
        - "江苏"
        - "四川"
        - "陕西"
        - "上海"

fileupload:
  tmp: /Users/rick/Space/tmp/fastdfs/tmp # 下载的临时目录
  local: # cd /Users/rick/Space/tmp/fileupload && http-server -p 7892
    root-path: /Users/rick/Space/tmp/fileupload
    server-url: http://localhost:7892/ # 映射到tmp目录

